services:
  mysql:
    image: mysql:8.0
    container_name: mysql_magasin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magasin_informatique
      MYSQL_USER: magasin_user
      MYSQL_PASSWORD: magasin_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  mysql_data: